// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqobrmrhtkhoztsruezv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxb2JybXJodGtob3p0c3J1ZXp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNzg3OTksImV4cCI6MjA2Njk1NDc5OX0.I1mth0Pi18jGVoNrcXbTubJLgjierxMC_SekJeee7fU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});